### ISSUE TITLE
JSON markup issues

### ISSUE THREAD

**Issue by ghost** [drewwilson/AutoSuggest#2]
Also, JSONLint points thats the keys "value", "name" should be inside quotes, but if I use them, the scripts has an error on this line :
var str = data[num].value; 

my json source in this case look like this when queried (names changed)
{ "items" :[ {"value":"692","name":"Ragdfma ACDFID"}, {"value":"686","name":"Altreine  AKKJVRAM"}, {"value":"428","name":"Tfadftc ARALKMA"}, {"value":"2100","name":"Ikrazdme BOUPOFRA"}] }

**Comment by django-rdf-tools** [comment]
I must add now that I also use jquery UI's autocomplete, and they use the "correct" flavour, the keys are quoted in the json data.

**Comment by django-rdf-tools** [comment]
Forget it
